spring:
  application:
    name: payment-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

razorpay:
  key: ${RAZORPAY_KEY}
  secret: ${RAZORPAY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:}

services:
  loan:
    url: ${LOAN_SERVICE_URL}

  customer:
    url: ${CUSTOMER_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
