package com.naveen.audit_service.entity;

public enum AuditAction {

    LOGIN,

    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,

    LOAN_CREATED,
    LOAN_UPDATED,
    LOAN_STATUS_CHANGED,

    CREDIT_DECISION_CREATED,
    CREDIT_DECISION_UPDATED,

    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,

    PAYMENT_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,

    REPAYMENT_CREATED,
    REPAYMENT_SUCCESS,
    REPAYMENT_FAILED,

    NOTIFICATION_CREATED,
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED
}
